local wk = require("which-key")
wk.register({
  ["["] = { "Previous buffer" },
  ["]"] = { "Next buffer" },
  ["="] = { "Val++" },
  ["-"] = { "Val--" },
  ["/"] = { "Comment" },
  -- ["1"] = { "Harpoon 1" },
  -- ["2"] = { "Harpoon 2" },
  -- ["3"] = { "Harpoon 3" },
  -- ["4"] = { "Harpoon 4" },
  -- ["5"] = { "Harpoon 5" },
  -- ["6"] = { "Harpoon 6" },
  -- ["7"] = { "Harpoon 7" },
  -- ["8"] = { "Harpoon 8" },
  j = { "Left pane" },
  k = { "Right pane" },
  u = { "Undo tree" },
  y = { "Copy to buffer" },
  e = { "Eslint fix all" },
  s = { "Save" },
  d = {
    name = "Diagnostics",
    n = "Next",
    p = "Previous",
    d = "Show diag",
  },
  f = {
    name = "File",
    f = { "Find File" },
    s = { "Grep string" },
    g = { "Find grep" },
    b = { "Find buffers" },
  },
  g = {
    name = "Git",
    g = { "Fugitive" },
    P = { "Preview diff" },
    p = { "Previous hunk" },
    n = { "Next hunk" },
    s = { "Stage hunk" },
    u = { "Undo hunk" },
    r = { "Reset hunk" },
    B = { "Blame line" },
    b = { "Toggle blame" },
    d = { "Diff" },
  },
  p = {
    name = "Project",
    v = { "File browser" }
  },
  l = {
    name = "lsp",
    r = "References",
    R = "Rename",
    d = "Definition",
    t = "Type definition",
    h = "Hover",
    i = "Implementation",
    s = "Signature help",
    f = "Format",
  }
}, { prefix = "<leader>" })
